-- bullet_manager.script
go.property("bullet_factory", "#bullet_factory")

function init(self)
	msg.post(".", "acquire_input_focus")
end

function on_message(self, message_id, message, sender)
	if message_id == hash("spawn_bullet") then
		factory.create(self.bullet_factory, message.pos, message.rot, {
			damage = message.damage or 10,
			speed = message.speed or 300,
			is_enemy = message.is_enemy or false,
			color = message.color or {1,1,1,1}
		})
	end

	if message_id == hash("enemy_died") then
		-- Тут можно добавить частицы, когда они появятся
		-- msg.post(".", "spawn_particles", { pos = message.pos })
	end
end