-- bullet.script
go.property("speed", 300)
go.property("damage", 10)
go.property("is_enemy", false)

function init(self)
	self.life = 3.0
end

function update(self, dt)
	local rot = go.get_rotation()
	local direction = vmath.rotate(rot, vmath.vector3(1, 0, 0)) 
	local pos = go.get_position()

	go.set_position(pos + direction * self.speed * dt)

	self.life = self.life - dt
	if self.life < 0 then go.delete() end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("trigger_response") and message.enter then
		local target_group = message.other_group

		-- Пуля игрока бьет врагов
		if not self.is_enemy and target_group == hash("enemy") then
			msg.post(message.other_id, "take_damage", { amount = self.damage })
			go.delete()

			-- Пуля врага бьет станцию/игрока
		elseif self.is_enemy and (target_group == hash("station") or target_group == hash("player")) then
			msg.post("@render:", "player_take_damage", { amount = self.damage })
			go.delete()
		end
	end
end