-- camera_shake.script

local time_for_refresh = 2
local current_time = 2
function init(self)
	msg.post(".", "acquire_input_focus")
	self.current_zoom = 1.0
	self.target_zoom = 1.0
end
function update(self, dt)


	if(current_time <= time_for_refresh) then return end

	local window_w, window_h = window.get_size()
	local scale_val = 1 -- По умолчанию портрет

	if window_w > window_h then
		scale_val = 1.4 -- Ландшафт
	end
	gui.set_scale(gui.get_node("active_panel"), vmath.vector3(scale_val, scale_val, 1))
	current_time = 0
end


local function shake(self, intensity, duration)
	-- Сохраняем исходную позицию, чтобы камера не "уехала" навсегда
	local initial_pos = vmath.vector3(0, 0, 0) 
	local elapsed = 0
	local interval = 0.02 -- Частота встряски

	-- Запускаем повторяющийся таймер
	timer.delay(interval, true, function(self, handle, time_elapsed)
		elapsed = elapsed + interval

		if elapsed >= duration then
			-- Время вышло: возвращаем камеру в ноль и удаляем таймер
			go.set_position(initial_pos)
			timer.cancel(handle) -- Теперь это сработает, так как мы передаем handle правильно
		else
			-- Генерируем случайное смещение
			local offset = vmath.vector3(
			math.random(-intensity, intensity),
			math.random(-intensity, intensity),
			0
		)
		go.set_position(initial_pos + offset)

		-- Постепенно уменьшаем силу тряски к концу (затухание)
		intensity = intensity * 0.9 
	end
end)
end

function on_message(self, message_id, message, sender)
if message_id == hash("shake") then
	shake(self, message.intensity or 5, message.duration or 0.2)
end
end