-- station.script

function init(self)
	-- 1. Создаем турель. Позиция 0,0,0.1 относительно родителя.
	local target_pos = vmath.vector3(0, 0, 0.1)
	self.turret_id = factory.create("#turret_factory", target_pos)

	-- 2. Мгновенная привязка через функцию, а не через сообщение
	-- Это сработает сразу в этом же кадре!
	go.set_parent(self.turret_id, go.get_id(), false) 

	-- Проверим теперь
	print("Турель теперь точно тут:", go.get_world_position(self.turret_id))
end

function on_message(self, message_id, message, sender)
	if message_id == hash("build_default_turret") then
		-- Станция создает турель прямо в своем центре (0,0)
		self.turret_id = factory.create("#turret_factory")

		-- Делаем турель ребенком станции
		msg.post(self.turret_id, "set_parent", { parent_id = go.get_id(), keep_world_transform = 0 })
	end
end