-- slot.script
local occupied = false
local turret_id = nil

function init(self)
	-- Сообщаем game_manager, что слот готов к работе
	msg.post("main:/logic#game_manager", "register_slot", { 
		slot_id = go.get_id()
	})
end

function on_message(self, message_id, message, sender)
	if message_id == hash("occupy_slot") then
		occupied = true
		turret_id = message.turret_id
		--go.set_color("#sprite", vmath.vector4(0.5, 1, 0.5, 1)) -- Зелёный = занято
	end

	if message_id == hash("free_slot") then
		occupied = false
		turret_id = nil
	--	go.set_color("#sprite", vmath.vector4(1, 1, 1, 1)) -- Белый = свободно
	end

	if message_id == hash("get_slot_state") then
		msg.post(sender, "slot_state_response", {
			slot_id = go.get_id(),
			occupied = occupied,
			position = go.get_world_position()
		})
	end
end