-- turret_trigger.script
function on_message(self, message_id, message, sender)
	if message_id == hash("trigger_response") then
		local parent = go.get_parent() -- Сама турель

		if message.enter then
			-- Проверяем, что вошел именно враг
			if message.other_group == hash("enemy") then
				msg.post(parent, "enemy_in_range", { enemy_id = message.other_id })
			end
		else
			if message.other_group == hash("enemy") then
				msg.post(parent, "enemy_left_range", { enemy_id = message.other_id })
			end
		end
	end
end